# Generated by Django 6.0 on 2026-08-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingportalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransfer',
            name='recipient_routing_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payee',
            name='routing_number',
            field=models.CharField(max_length=100),
        ),
    ]
