# Generated by Django 6.0 on 2026-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingportalapp', '0002_alter_externaltransfer_recipient_routing_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
