# Generated by Django 6.0 on 2026-08-23 08:24

from django.db import migrations
import random


def generate_unique_account_number(apps):
    """Generate a unique 10-digit account number."""
    Account = apps.get_model('onlinebankingportalapp', 'Account')
    while True:
        number = str(random.randint(1000000000, 9999999999))
        if not Account.objects.filter(account_number=number).exists():
            return number


def populate_account_numbers(apps, schema_editor):
    Account = apps.get_model('onlinebankingportalapp', 'Account')
    for account in Account.objects.filter(account_number__isnull=True):
        account.account_number = generate_unique_account_number(apps)
        account.save(update_fields=['account_number'])


def create_accounts_for_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Account = apps.get_model('onlinebankingportalapp', 'Account')

    for user in User.objects.all():
        if not Account.objects.filter(user=user).exists():
            Account.objects.create(
                user=user,
                name=f"{user.username}'s Checking",
                account_type='checking',
                balance=0.00,
                account_number=generate_unique_account_number(apps),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingportalapp', '0003_account_account_number'),
    ]

    operations = [
        migrations.RunPython(populate_account_numbers),
        migrations.RunPython(create_accounts_for_existing_users),
    ]
