# Generated by Django 6.0 on 2026-08-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingportalapp', '0004_populate_account_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
