# Generated by Django 6.0 on 2026-08-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingportalapp', '0005_alter_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Naira (₦)'), ('USD', 'Dollar ($)')], default='NGN', max_length=3),
        ),
    ]
