# Generated by Django 6.0 on 2026-08-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebankingportalapp', '0006_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransfer',
            name='transfer_type',
            field=models.CharField(choices=[('ACH', 'ACH'), ('WIRE', 'Wire'), ('NIP', 'NIP'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20),
        ),
    ]
